version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - revive  # replaces golint
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - gocyclo
    - misspell
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
