version: 2

run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - gocyclo
    - misspell
    - gocritic

formatters:
  enable:
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/ethan-k/pomodoro-cli

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Ignore long lines in generated files
    - path: cmd/root.go
      linters:
        - lll
    
    # Ignore certain revive issues
    - linters:
        - revive
      text: "should have comment"
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

