version: 2

run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp
    disabled-checks:
      - assignOp
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - "(*github.com/ethan-k/pomodoro-cli/internal/db.InternalDB).Close"
      - "(*database/sql.DB).Close"
      - "(*database/sql.Rows).Close"
  gosec:
    excludes:
      - G204  # subprocess with variable
      - G301  # directory permissions
      - G304  # file inclusion via variable
      - G306  # WriteFile perms

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - gocyclo
    - misspell
    - gocritic

formatters:
  enable:
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/ethan-k/pomodoro-cli

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Ignore long lines in generated files
    - path: cmd/root.go
      linters:
        - lll
    
    # Ignore revive issues that are too noisy for this project
    - linters:
        - revive
      text: "should have comment"
    - linters:
        - revive
      text: "package-comments"
    - linters:
        - revive
      text: "exported"
    - path: ^cmd/.*
      linters:
        - revive
      text: "unused-parameter"
    - path: ^internal/.*
      linters:
        - revive
      text: "unused-parameter"
    - path: ^cmd/break.go$
      linters:
        - revive
      text: "var-naming"
    - linters:
        - gocritic
      text: "assignOp"
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
